INSERT INTO APP_M_INVENTARIO.INVENTORY (INVENTORY_ID,AMOUNT,STOCK,AVAILABLE,MIN_QUANTITY,MAX_QUANTITY,STORE_ID,PRODUCT_ID) VALUES (INVENTORY_SEQ.NEXTVAL,2,0,2,10,50,4,21);
INSERT INTO APP_M_INVENTARIO.INVENTORY (INVENTORY_ID,AMOUNT,STOCK,AVAILABLE,MIN_QUANTITY,MAX_QUANTITY,STORE_ID,PRODUCT_ID) VALUES (INVENTORY_SEQ.NEXTVAL,4,2,2,10,30,5,9);
INSERT INTO APP_M_INVENTARIO.INVENTORY (INVENTORY_ID,AMOUNT,STOCK,AVAILABLE,MIN_QUANTITY,MAX_QUANTITY,STORE_ID,PRODUCT_ID) VALUES (INVENTORY_SEQ.NEXTVAL,4,0,4,10,50,7,21);
INSERT INTO APP_M_INVENTARIO.INVENTORY (INVENTORY_ID,AMOUNT,STOCK,AVAILABLE,MIN_QUANTITY,MAX_QUANTITY,STORE_ID,PRODUCT_ID) VALUES (INVENTORY_SEQ.NEXTVAL,16,0,16,10,30,1,9);
