INSERT INTO APP_M_INVENTARIO.LOCATION (LOCATION_ID,NAME) VALUES (LOCATION_SEQ.NEXTVAL,'Medellín');
INSERT INTO APP_M_INVENTARIO.LOCATION (LOCATION_ID,NAME) VALUES (LOCATION_SEQ.NEXTVAL,'Cali');
INSERT INTO APP_M_INVENTARIO.LOCATION (LOCATION_ID,NAME) VALUES (LOCATION_SEQ.NEXTVAL,'Bogotá');
INSERT INTO APP_M_INVENTARIO.LOCATION (LOCATION_ID,NAME) VALUES (LOCATION_SEQ.NEXTVAL,'Japón');
INSERT INTO APP_M_INVENTARIO.LOCATION (LOCATION_ID,NAME) VALUES (LOCATION_SEQ.NEXTVAL,'China');
