INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Juan David Angel Mejía',1023485697,1);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Alejandra Patiño Agudelo',1020458741,2);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Diego Echeverri Londoño',43562147,3);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Sara Catherine Durán Pacheco',1030456214,1);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Juan Daniel Rodriguez Jimenez',45369217,2);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Olga Lucía Jaramillo Palacio',43658971,3);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Laura Caro Puerta',1020369584,1);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Diana Saldarriaga Gil',45123698,2);
INSERT INTO APP_M_INVENTARIO.MANAGER (MANAGER_ID,NAME,IDENTIFICATION,LOCATION_ID) VALUES (MANAGER_SEQ.NEXTVAL,'Luis David Pérez López',1050236541,3);
