INSERT INTO APP_M_INVENTARIO.PROVIDER (PROVIDER_ID,NAME,LOCATION_ID,CONTACT) VALUES (PROVIDER_SEQ.NEXTVAL,'Honda',4,'326547854');
INSERT INTO APP_M_INVENTARIO.PROVIDER (PROVIDER_ID,NAME,LOCATION_ID,CONTACT) VALUES (PROVIDER_SEQ.NEXTVAL,'Benda',5,'8615214879632');
INSERT INTO APP_M_INVENTARIO.PROVIDER (PROVIDER_ID,NAME,LOCATION_ID,CONTACT) VALUES (PROVIDER_SEQ.NEXTVAL,'Yamaha',4,'362135632');
INSERT INTO APP_M_INVENTARIO.PROVIDER (PROVIDER_ID,NAME,LOCATION_ID,CONTACT) VALUES (PROVIDER_SEQ.NEXTVAL,'Suzuki',4,'369821458');
INSERT INTO APP_M_INVENTARIO.PROVIDER (PROVIDER_ID,NAME,LOCATION_ID,CONTACT) VALUES (PROVIDER_SEQ.NEXTVAL,'Ariic',5,'8613265481972');
