INSERT INTO APP_M_INVENTARIO.TAX (TAX_ID,NAME,RATE,DESCRIPTION) VALUES (TAX_SEQ.NEXTVAL,'IVA',19,'Impuesto al valor agregado');
INSERT INTO APP_M_INVENTARIO.TAX (TAX_ID,NAME,RATE,DESCRIPTION) VALUES (TAX_SEQ.NEXTVAL,'INC',8,'Impuesto nacional al consumo');
